# Generated by Django 6.0.6 on 2026-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.BooleanField(),
        ),
    ]
